.Dd November 21, 2019
.Dt ATOMX 1
.Os wmutils
.Sh NAME
.Nm atomx
.Nd manage X atoms on a window
.Sh SYNOPSIS
.Nm atomx
.Op Fl d
.Ar atom
.Op Ar =value
.Ar wid
.Sh DESCRIPTION
.Nm
will print, add, change and remove X atoms on the window with ID
.Ar wid .
By default
.Nm
will print the value of the atom
.Ar atom
if it exists.
.Pp
To set an atom on a window, you must specify it as
.Ar atom=value .
.Bl -tag -width Ds
.It Fl d
Delete atom
.Ar atom
from the window.
.Sh ENVIRONMENT
.Nm
acts on the X display specified by the
.Ev DISPLAY
variable.
.Sh EXAMPLES
Print value of property "WM_CLASS"
.Dl $ atomx WM_CLASS 0x00e00005
.Pp
Change window name to "atomx"
.Dl $ atomx WM_NAME=atomx 0x00e00005
.Pp
Delete property "IS_FULLSCREEN" on a window
.Dl $ atomx -d IS_FULLSCREEN 0x00e00005
