.TH WMV 1 "December 2014" wmutils

.SH NAME
wmv - move windows (relatively)

.SH SYNOPSIS
.B wmv
.I <x> <y> <wid>

.SH DESCRIPTION
.B wmv
will move a window to another position using relative coordinates

.TP
.I <x>
much pixel
.I <wid>
should move on the X axis
.TP
.I <y>
much pixel
.I <wid>
should move on the Y axis

.SH ENVIRONMENT
.B wmv
follows the variable
.I DISPLAY
to set X.org display to act on.
