.TH WNAME 1 "December 2014" wmutils

.SH NAME
wname - print window name

.SH SYNOPSIS
.B wname
.IR <wid>\  [ wid.. ]

.SH DESCRIPTION
.B wname
will print the name of the windows given as arguments, printing one name per
line

.SH ENVIRONMENT
.B wname
follows the variable
.I DISPLAY
to set X.org display to act on.
