.TH WTF 1 "December 2014" wmutils

.SH NAME
wtf - transfert window focus

.SH SYNOPSIS
.BI wtf\  <wid>

.SH DESCRIPTION
.B wtf
will set the keyboardi input focus to the window
.I <wid>
if it exists and is viewable

.SH ENVIRONMENT
.B wtf
follows the variable
.I DISPLAY
to set X.org display to act on.
