.TH WTP 1 "December 2014" wmutils

.SH NAME
wtp - teleport window (absolutely)

.SH SYNOPSIS
.B wtp
.I <x> <y> <w> <h> <wid>

.SH DESCRIPTION
.B wtp
will move (or teleport) a window to the position given as arguments, and set
its size accordingly. Value are absolute value from the the left hand-corner

.TP
.B <x>
X offset to set for
.I <wid> 
.TP
.B <y>
Y offset to set for
.I <wid>
.TP
.B <w>
width to set for
.I <wid>
.TP
.B <h>
height to set for
.I <wid>

.SH ENVIRONMENT
.B wtp
follows the variable
.I DISPLAY
to set X.org display to act on.
